/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as GateRouteImport } from './routes/gate'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiV1AnalyticsRouteImport } from './routes/api/v1/analytics'
import { Route as ApiV1EvaluateRouteImport } from './routes/api/v1/evaluate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const GateRoute = GateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AnalyticsRoute = ApiV1AnalyticsRouteImport.update({
  id: '/api/v1/analytics',
  path: '/api/v1/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EvaluateRoute = ApiV1EvaluateRouteImport.update({
  id: '/api/v1/evaluate',
  path: '/api/v1/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/gate': typeof GateRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/receipts': typeof ReceiptsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/v1/analytics': typeof ApiV1AnalyticsRoute
  '/api/v1/evaluate': typeof ApiV1EvaluateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/gate': typeof GateRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/receipts': typeof ReceiptsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/v1/analytics': typeof ApiV1AnalyticsRoute
  '/api/v1/evaluate': typeof ApiV1EvaluateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/gate': typeof GateRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/receipts': typeof ReceiptsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/v1/analytics': typeof ApiV1AnalyticsRoute
  '/api/v1/evaluate': typeof ApiV1EvaluateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/gate'
    | '/integrations'
    | '/login'
    | '/policies'
    | '/privacy'
    | '/receipts'
    | '/review'
    | '/settings'
    | '/terms'
    | '/api/v1/analytics'
    | '/api/v1/evaluate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/gate'
    | '/integrations'
    | '/login'
    | '/policies'
    | '/privacy'
    | '/receipts'
    | '/review'
    | '/settings'
    | '/terms'
    | '/api/v1/analytics'
    | '/api/v1/evaluate'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/gate'
    | '/integrations'
    | '/login'
    | '/policies'
    | '/privacy'
    | '/receipts'
    | '/review'
    | '/settings'
    | '/terms'
    | '/api/v1/analytics'
    | '/api/v1/evaluate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  GateRoute: typeof GateRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  PoliciesRoute: typeof PoliciesRoute
  PrivacyRoute: typeof PrivacyRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiV1AnalyticsRoute: typeof ApiV1AnalyticsRoute
  ApiV1EvaluateRoute: typeof ApiV1EvaluateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate': {
      id: '/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof GateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/analytics': {
      id: '/api/v1/analytics'
      path: '/api/v1/analytics'
      fullPath: '/api/v1/analytics'
      preLoaderRoute: typeof ApiV1AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/evaluate': {
      id: '/api/v1/evaluate'
      path: '/api/v1/evaluate'
      fullPath: '/api/v1/evaluate'
      preLoaderRoute: typeof ApiV1EvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  GateRoute: GateRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  PoliciesRoute: PoliciesRoute,
  PrivacyRoute: PrivacyRoute,
  ReceiptsRoute: ReceiptsRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiV1AnalyticsRoute: ApiV1AnalyticsRoute,
  ApiV1EvaluateRoute: ApiV1EvaluateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
